#!/usr/bin/sh

pkglist=(
astro-build.astro-vscode
AykutSarac.jsoncrack-vscode
bierner.color-info
bmewburn.vscode-intelephense-client
bradlc.vscode-tailwindcss
byCedric.vscode-expo
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
codingyu.laravel-goto-view
daverik.hextorgb
dbaeumer.vscode-eslint
dlasagno.rasi
eamodio.gitlens
esbenp.prettier-vscode
flowtype.flow-for-vscode
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
ID-wj.transparent-win
janisdd.vscode-edit-csv
jasonnutter.search-node-modules
kamikillerto.vscode-colorize
magicstack.MagicPython
mgesbert.python-path
mgmcdermott.vscode-language-babel
ms-azuretools.vscode-docker
ms-dotnettools.csharp
ms-dotnettools.vscode-dotnet-runtime
ms-python.black-formatter
ms-python.flake8
ms-python.python
ms-python.vscode-pylance
ms-vscode-remote.remote-containers
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.vscode-typescript-next
ms-vsliveshare.vsliveshare
msjsdiag.vscode-react-native
Perkovec.emoji
PKief.material-icon-theme
pranaygp.vscode-css-peek
Prisma.prisma
quicktype.quicktype
redhat.java
s-nlf-fh.glassit
shufo.vscode-blade-formatter
twxs.cmake
usernamehw.errorlens
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
vscode-icons-team.vscode-icons
Vue.volar
Vue.vscode-typescript-vue-plugin
xabikos.JavaScriptSnippets
xabikos.ReactSnippets
xdebug.php-pack
zobo.php-intellisense
)

for i in "${pkglist[@]}"; do 
    echo "installing $i"
    code --install-extension  $i --force
done
