#: My font config for kitty
font_size 9.5
font_family JetBrains Nerd Regular
font_bold JetBrains Nerd Bold
font_italic JetBrains Nerd Italic


#: My kitty aparience customization

background_opacity 0.95
# background_blur 20
allow_remote_control yes

## Cursor

cursor_shape          block
cursor_blink_interval 0.5
cursor_stop_blinking_after 0
shell_integration     no-cursor


#: Neovim Optimizations

term xterm-kitty
undercurl_style thin-sparse
scrollback_lines 10000

repain_delay 10
input_delay 3
sync_to_monitor yes

allow_remote_control yes
listen_on unix:/tmp/kitty
enable_audio_bell no
draw_minimal_borders no
draw_window_borders_for_single_window no


#: Key mappings

map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+enter launch --cwd=current
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9
# wheel_scroll_multiplier 400.0
# touch_scroll_multiplier 5.0

#KITTY Theme my theme
# include my_theme.conf
include sonokai_shusia.conf

# Pestañas y ventanas
tab_bar_style powerline
# tab_separator " ┇"
tab_title_template  "{index}: {tab.active_oldest_wd}"
# tab_bar_style  separator
tab_bar_margin_width 0
tab_bar_padding_width 0


#: Window padding (Adjust these numbers to your liking)
remember_window_size no

initial_window_width 190c
initial_window_height 55c

placement_strategy center
resize_in_steps yes
window_padding_with 0
window_margin_with 0

resize_draw_strategy static

wayland_titlebar_color background

# linux_display_server x11
linux_display_server auto
hide_window_decorations yes
wayland_titlebar_color #242424
wayland_enable_ime yes



