
#: My font config for kitty
font_size 11
font_family JetBrains Nerd Medium
font_bold JetBrains Nerd Bold
font_italic JetBrains Nerd Italic


#: My kitty aparience customization

enable_audio_bell no
background_opacity 0.9
background_blur 10
allow_remote_control yes

#: Keybindings
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+enter launch --cwd=current
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9


#KITTY Theme my theme
# include my_theme.conf
include sonokai_shusia.conf

# Pestañas y ventanas
tab_bar_style powerline
# tab_separator " ┇"
tab_title_template  "{index}: {tab.active_oldest_wd}"
# tab_bar_style  separator
tab_bar_margin_width 0
linux_display_server x11



# Window preferences and layouts

enabled_layouts fat,splits,grid

initial_window_width 164c
initial_window_height 48c

#: Window padding (Adjust these numbers to your liking)
window_padding_width 0

placement_strategy center

resize_draw_strategy static



