#background #1E1E1E
#font-family Noto Sans
tab_bar_edge    bottom
tab_bar_margin_width    1
tab_bar_margin_height    1 0
tab_bar_style    fade
tab_fade    0 
# tab_title_template          "{title}"
# active_tab_title_template   "{fmt.bg._080808}{fmt.fg._80a0ff}{fmt.fg.default}{fmt.bg._80a0ff}{fmt.fg._080808}{title}{fmt.fg.default}{fmt.bg.default}{fmt.fg._80a0ff}{fmt.fg.default}"
# Color de la barra de pestañas
active_tab_background #323232  
inactive_tab_background #1c1c1c
active_tab_foreground #C78315  
inactive_tab_foreground #888888
