background #2d2a2e
foreground #e3e1e4

# selection_background #423f46
# selection_foreground #e3e1e4

cursor #928374
cursor_text_color background

# tabs colors

active_tab_background #323232
inactive_tab_background #1c1c1c
active_tab_foreground #C78315
inactive_tab_foreground #888888
inactive_tab_font_style normal
active_tab_font_style bold
